GPUID: 0
WORKERS: 1
PRINT_FREQ: 10
SAVE_FREQ: 10
PIN_MEMORY: False
OUTPUT_DIR: 'output'

CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASET:
  DATASET: 360CC
  ROOT: "/media/deeppc/data/work_space/guo_keti/CRNN_Chinese_Characters_Rec-stable/CRNN_Chinese_Characters_Rec-stable/data_bj_nums/images/"
  CHAR_FILE: '/media/deeppc/data/work_space/guo_keti/CRNN_Chinese_Characters_Rec-stable/CRNN_Chinese_Characters_Rec-stable/data_bj_nums/labels/char_std_12.txt'
  JSON_FILE: {'train': '/media/deeppc/data/work_space/guo_keti/CRNN_Chinese_Characters_Rec-stable/CRNN_Chinese_Characters_Rec-stable/data_bj_nums/labels/train.txt', 'val': '/media/deeppc/data/work_space/guo_keti/CRNN_Chinese_Characters_Rec-stable/CRNN_Chinese_Characters_Rec-stable/data_bj_nums/labels/val.txt'}
#  JSON_FILE: {'train': 'H:/DL-DATASET/360M/train.txt', 'val': 'H:/DL-DATASET/360M/test.txt'}
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  STD: 0.193
  MEAN: 0.588
  ALPHABETS: ''

TRAIN:
  BATCH_SIZE_PER_GPU: 64
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 5000
  RESUME:
    IS_RESUME: False
    FILE: ''
  OPTIMIZER: 'adam'
  LR: 0.0001
  WD: 0.0
  LR_STEP: [60, 80]
  LR_FACTOR: 0.1
  MOMENTUM: 0.0
  NESTEROV: False
  RMSPROP_ALPHA:
  RMSPROP_CENTERED:
  FINETUNE:
    IS_FINETUNE: True
    FINETUNE_CHECKPOINIT:  'output/checkpoints/mixed_second_finetune_acc_97P7.pth'
    FREEZE: true

TEST:
  BATCH_SIZE_PER_GPU: 64
  SHUFFLE: True  # for random test rather than test on the whole validation set
  NUM_TEST_BATCH: 1000
  NUM_TEST_DISP: 10

MODEL:
  NAME: 'crnn'
  IMAGE_SIZE:
    OW: 280 # origial width: 280
    H: 32
    W: 64   # resized width: 160
  NUM_CLASSES: 0
  NUM_HIDDEN: 256

